# Generated by Django 5.2.17 on 2026-10-05 08:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('also_called', models.CharField(blank=True, max_length=120)),
                ('scientific_name', models.CharField(blank=True, max_length=120)),
                ('family', models.CharField(choices=[('cereal', 'Cereal'), ('legume', 'Legume'), ('root_tuber', 'Root and tuber'), ('solanaceae', 'Solanaceae (tomato family)'), ('malvaceae', 'Malvaceae (okro family)')], max_length=20)),
                ('fixes_nitrogen', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('group', models.CharField(choices=[('weights', 'Score weights'), ('calendar', 'Season calendar'), ('water', 'Water'), ('nutrients', 'Nutrient shares'), ('thresholds', 'Nutrient thresholds (mg/kg)')], max_length=20)),
                ('kind', models.CharField(choices=[('number', 'Number'), ('month_day', 'Date in the year (MM-DD)')], default='number', max_length=10)),
                ('value', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CropPairRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verdict', models.CharField(choices=[('good', 'Good together'), ('avoid', 'Avoid together')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crop_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crops.crop')),
                ('crop_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crops.crop')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['crop_a__name', 'crop_b__name'],
                'constraints': [models.UniqueConstraint(fields=('crop_a', 'crop_b'), name='unique_crop_pair'), models.CheckConstraint(condition=models.Q(('crop_a__lt', models.F('crop_b'))), name='crop_pair_ordered')],
            },
        ),
        migrations.CreateModel(
            name='CropRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('version', models.PositiveIntegerField(editable=False)),
                ('ph_min', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH minimum')),
                ('ph_ideal_low', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH ideal low')),
                ('ph_ideal_high', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH ideal high')),
                ('ph_max', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH maximum')),
                ('n_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='nitrogen demand')),
                ('p_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='phosphorus demand')),
                ('k_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='potassium demand')),
                ('water_low_mm', models.PositiveIntegerField(verbose_name='water need, low (mm)')),
                ('water_high_mm', models.PositiveIntegerField(verbose_name='water need, high (mm)')),
                ('days_min', models.PositiveIntegerField(verbose_name='days to maturity, minimum')),
                ('days_max', models.PositiveIntegerField(verbose_name='days to maturity, maximum')),
                ('temp_low_c', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='temperature low (°C)')),
                ('temp_high_c', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='temperature high (°C)')),
                ('planting_window', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('requires_standing_water', models.BooleanField(default=False)),
                ('exempt_from_season_length', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='crops.crop')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['crop__name', '-version'],
                'constraints': [models.UniqueConstraint(fields=('crop', 'version'), name='unique_requirement_version')],
            },
        ),
        migrations.CreateModel(
            name='RotationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=10)),
                ('match', models.CharField(choices=[('pattern', 'Previous → next'), ('repeat_third_season', 'Same crop a third season running')], default='pattern', max_length=25)),
                ('previous_family', models.CharField(blank=True, choices=[('cereal', 'Cereal'), ('legume', 'Legume'), ('root_tuber', 'Root and tuber'), ('solanaceae', 'Solanaceae (tomato family)'), ('malvaceae', 'Malvaceae (okro family)')], max_length=20)),
                ('next_family', models.CharField(blank=True, choices=[('cereal', 'Cereal'), ('legume', 'Legume'), ('root_tuber', 'Root and tuber'), ('solanaceae', 'Solanaceae (tomato family)'), ('malvaceae', 'Malvaceae (okro family)')], max_length=20)),
                ('effect', models.CharField(choices=[('bonus', 'Bonus (+40%)'), ('small_bonus', 'Small bonus (+20%)'), ('penalty', 'Penalty (−30%)'), ('strong_penalty', 'Strong penalty (−60%)'), ('block', 'Block (crop removed)')], max_length=20)),
                ('reason', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('next_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crops.crop')),
                ('previous_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crops.crop')),
            ],
            options={
                'ordering': ['code', 'created_at'],
                'indexes': [models.Index(fields=['code'], name='crops_rotat_code_f7bd6d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('match', 'pattern'), models.Q(models.Q(models.Q(('previous_family', ''), _negated=True), ('previous_crop__isnull', True)), models.Q(('previous_family', ''), ('previous_crop__isnull', False)), _connector='OR'), models.Q(models.Q(models.Q(('next_family', ''), _negated=True), ('next_crop__isnull', True)), models.Q(('next_family', ''), ('next_crop__isnull', False)), _connector='OR')), models.Q(('match', 'repeat_third_season'), ('next_crop__isnull', True), ('next_family', ''), ('previous_crop__isnull', True), ('previous_family', '')), _connector='OR'), name='rotation_rule_sides')],
            },
        ),
    ]
