# Generated by Django 5.2.17 on 2026-10-05 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_season_cropping_method_intendedcrop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField()),
                ('ph', models.FloatField(verbose_name='pH')),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('moisture_pct', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True, verbose_name='EC')),
                ('source', models.CharField(choices=[('sensor', 'Sensor'), ('manual', 'Typed in')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='farms.farm')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='farms.season')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['farm', '-taken_at'], name='readings_so_farm_id_a3d7fa_idx')],
            },
        ),
    ]
