# Generated by Django 5.2.17 on 2026-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_rules',
            field=models.BooleanField(default=False, help_text='May approve crop requirements, pair rules, rotation rules and verify score settings. Set from RULE_APPROVER_EMAIL by seed_admins.'),
        ),
    ]
