# Generated by Django 5.2.17 on 2026-10-05 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9 \\-]{6,18}[0-9]$', 'Enter a phone number using digits, spaces or dashes, e.g. 0803 123 4567.')])),
                ('language', models.CharField(choices=[('hausa', 'Hausa'), ('nupe', 'Nupe'), ('gbagyi', 'Gbagyi (Gwari)'), ('english', 'English'), ('yoruba', 'Yoruba'), ('igbo', 'Igbo'), ('other', 'Other')], default='hausa', max_length=20)),
                ('village', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('size_ha', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='size (hectares)')),
                ('water_source', models.CharField(choices=[('rain_fed', 'Rain-fed'), ('irrigated', 'Irrigated'), ('fadama', 'Fadama')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='farms.farmer')),
            ],
            options={
                'ordering': ['farmer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('label', models.CharField(choices=[('rainy', 'Rainy season'), ('dry', 'Dry season')], max_length=10)),
                ('cropping_method', models.CharField(choices=[('mono', 'Mono cropping'), ('mixed', 'Mixed cropping')], max_length=10)),
                ('planting_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recommended', 'Recommended'), ('closed', 'Closed')], default='draft', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='farms.farm')),
            ],
            options={
                'ordering': ['farm', 'planting_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['village'], name='farms_farme_village_be8d16_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['phone'], name='farms_farme_phone_a43caa_idx'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('farm',), name='one_draft_season_per_farm', violation_error_message='This farm already has an open (draft) season.'),
        ),
    ]
