# Generated by Django 5.2.17 on 2026-10-05 08:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='cropping_method',
            field=models.CharField(blank=True, choices=[('mono', 'Mono cropping'), ('mixed', 'Mixed cropping')], max_length=10),
        ),
        migrations.CreateModel(
            name='IntendedCrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crops.crop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intended_crops', to='farms.season')),
            ],
            options={
                'ordering': ['crop__name'],
                'constraints': [models.UniqueConstraint(fields=('season', 'crop'), name='unique_intended_crop')],
            },
        ),
        migrations.CreateModel(
            name='PreviousCrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_text', models.CharField(blank=True, max_length=120)),
                ('seasons_ago', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crops.crop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_crops', to='farms.season')),
            ],
            options={
                'ordering': ['seasons_ago', 'crop__name', 'free_text'],
                'constraints': [models.CheckConstraint(condition=models.Q(('crop__isnull', False), models.Q(('free_text', ''), _negated=True), _connector='OR'), name='previous_crop_has_crop_or_text'), models.CheckConstraint(condition=models.Q(('seasons_ago__gte', 1), ('seasons_ago__lte', 3)), name='previous_crop_seasons_ago_1_to_3')],
            },
        ),
    ]
